### ISSUE TITLE
Select a PHP mirror?

### ISSUE THREAD

**Issue by Stratus3D** [Stratus3D/asdf-php#2]
@HashNuke @tuvistavie I need your advice on a issue I'm facing with this plugin. Basically, from the PHP website when you select a version they prompt you to pick a mirror (https://secure.php.net/downloads.php). I can however download the archive directly from php.net if I tinker with the URL. I don't really want to download from php.net because it seems like they don't want people doing that. Using a mirror would be fine, but they I have to figure out which mirror to use, and short of testing every mirror, there isn't a good way to do that. Another option would be to clone the Git repo mirror on GitHub and checkout the appropriate tag. So far using GitHub seems like the best option. Though it's much easier to just download an archive, which is what I'd like to do.

Do you guys have any thoughts on this? Have you ever run into similar issues with the other plugins?

Thanks!

**Comment by Stratus3D** [comment]
Oh, I didn't realize I can download an archive of each release directly off of GitHub. That should probably be fine. And since it's an archive hopefully it will be less strain on GitHub's infrastructure.

**Comment by tuvistavie** [comment]
I just finished writing a short script to download from the closest mirror, if possible :smile: 

https://gist.github.com/tuvistavie/cec8298ab95e45b94c60c968fe27c352

**Comment by Stratus3D** [comment]
Nice! I'll see how it goes with GitHub and go from there. Thanks!
